In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('DataSetKopi.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Expresso' 70.0 35000.0]
 ['Americano' 30.0 35000.0]
 ['Macchiato' 30.0 65000.0]
 ['Cappuchino' 65.0 50000.0]
 ['Americano' 45.0 45000.0]
 ['Macchiato' 35.0 nan]
 ['Cappuchino' 55.0 60000.0]
 ['Expresso' 0.0 85000.0]
 ['Americano' 85.0 40000.0]
 ['Expresso' 80.0 65000.0]
 ['Macchiato' nan 55000.0]
 ['Cappuchino' 45.0 40000.0]
 ['Expresso' 110.0 70000.0]
 ['Macchiato' 75.0 nan]
 ['Cappuchino' 85.0 50000.0]
 ['Americano' 150.0 30000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes']


In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,  random_state = 0)

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [7]:
print(x)

[['Expresso' 70.0 35000.0]
 ['Americano' 30.0 35000.0]
 ['Macchiato' 30.0 65000.0]
 ['Cappuchino' 65.0 50000.0]
 ['Americano' 45.0 45000.0]
 ['Macchiato' 35.0 51785.71428571428]
 ['Cappuchino' 55.0 60000.0]
 ['Expresso' 0.0 85000.0]
 ['Americano' 85.0 40000.0]
 ['Expresso' 80.0 65000.0]
 ['Macchiato' 64.0 55000.0]
 ['Cappuchino' 45.0 40000.0]
 ['Expresso' 110.0 70000.0]
 ['Macchiato' 75.0 51785.71428571428]
 ['Cappuchino' 85.0 50000.0]
 ['Americano' 150.0 30000.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [12]:
print(x_train)

[[0.0 1.0 0.0 0.0 55.0 60000.0]
 [0.0 0.0 0.0 1.0 64.0 55000.0]
 [1.0 0.0 0.0 0.0 45.0 45000.0]
 [1.0 0.0 0.0 0.0 30.0 35000.0]
 [0.0 1.0 0.0 0.0 85.0 50000.0]
 [0.0 0.0 1.0 0.0 70.0 35000.0]
 [1.0 0.0 0.0 0.0 150.0 30000.0]
 [0.0 0.0 1.0 0.0 80.0 65000.0]
 [1.0 0.0 0.0 0.0 85.0 40000.0]
 [0.0 0.0 1.0 0.0 110.0 70000.0]
 [0.0 1.0 0.0 0.0 45.0 40000.0]
 [0.0 0.0 0.0 1.0 35.0 51785.71428571428]]


In [13]:
print(x_test)

[[0.0 1.0 0.0 0.0 65.0 50000.0]
 [0.0 0.0 0.0 1.0 75.0 51785.71428571428]
 [0.0 0.0 1.0 0.0 0.0 85000.0]
 [0.0 0.0 0.0 1.0 30.0 65000.0]]


In [14]:
print(y_train)

[0 0 1 1 0 0 1 1 0 0 1 1]


In [15]:
print(y_test)

[0 1 1 0]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[0.0 1.0 0.0 -0.44721359549995787 -0.49365945298427505
  0.9790072907519946]
 [0.0 0.0 0.0 2.2360679774997894 -0.2188387265806581 0.5688496228060217]
 [1.0 0.0 0.0 -0.44721359549995787 -0.7990158156549605
  -0.2514657130859238]
 [1.0 0.0 0.0 -0.44721359549995787 -1.2570503596609888
  -1.0717810489778694]
 [0.0 1.0 0.0 -0.44721359549995787 0.42240963502778145
  0.15869195486004897]
 [0.0 0.0 1.0 -0.44721359549995787 -0.035624908978246786
  -1.0717810489778694]
 [1.0 0.0 0.0 -0.44721359549995787 2.4072259923872372 -1.481938716923842]
 [0.0 0.0 1.0 -0.44721359549995787 0.2697314536924387 1.3891649586979673]
 [1.0 0.0 0.0 -0.44721359549995787 0.42240963502778145
  -0.6616233810318966]
 [0.0 0.0 1.0 -0.44721359549995787 1.1858005417044952 1.79932262664394]
 [0.0 1.0 0.0 -0.44721359549995787 -0.7990158156549605
  -0.6616233810318966]
 [0.0 0.0 0.0 2.2360679774997894 -1.104372178325646 0.3051768362693247]]


In [18]:
print(x_test)

[[0.0 1.0 0.0 -0.44721359549995787 -0.18830309031358955
  0.15869195486004897]
 [0.0 0.0 0.0 2.2360679774997894 0.11705327235709596 0.3051768362693247]
 [0.0 0.0 1.0 -0.44721359549995787 -2.173119447673045 3.0297956304818583]
 [0.0 0.0 0.0 2.2360679774997894 -1.2570503596609888 1.3891649586979673]]
